package com.te.lms.constant;

public class Constants {

	public static final String FETCH_MENTOR_SUCESFULLY = "FETCH_MENTOR_SUCESFULLY ";
	public static final String REGISTER_MENTOR_SUCESFULLY = "REGISTER_MENTOR_SUCESFULLY";
	public static final String REGISTER_EMPLOYEE_SUCESFULLY = "REGISTER_EMPLOYEE_SUCESFULLY";

	public static final String FETCH_EMPLOYEE_SUCESFULLY = "FETCH_EMPLOYEE_SUCESFULLY";
	public static final String UPDATE_EMPLOYEE_SUCESFULLY = "UPDATE_EMPLOYEE_SUCESFULLY";
	public static final String REMOVE_EMPLOYEE_SUCESFULLY = "REMOVE_EMPLOYEE_SUCESFULLY";

	public static final String LOGIN_SUCESFULLY = "LOGIN_SUCESFULLY";

	public static final String REGISTER_ADMIN_SUCESFULLY = "REGISTER_ADMIN_SUCESFULLY";
	public static final String FETCH_ADMIN_SUCESFULLY = "FETCH_ADMIN_SUCESFULLY";
	public static final String UPDATE_ADMIN_SUCESFULLY = "UPDATE_ADMIN_SUCESFULLY";
	public static final String REMOVE_ADMIN_SUCESFULLY = "REMOVE_ADMIN_SUCESFULLY";

}
